### ISSUE TITLE
Can't sub-query

### ISSUE THREAD

**Issue by oakbrad** [mschuerig/beets-top#2]
Thanks for this, I realize this project is old but I don't know enough Python to figure out the error I'm getting when trying to sub-query

for commands like:
beet top 42 artists by time in year:1990
beet top artists in genre:jazz

```
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.7', 'console_scripts', 'beet')()
  File "/home/brad/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/home/brad/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/top.py", line 124, in func
    top(lib, args, opts)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/top.py", line 69, in top
    params = parse_args(args, opts)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/top.py", line 105, in parse_args
    table2, subvals2 = library.get_query(args).statement()
AttributeError: 'module' object has no attribute 'get_query'
```

Any help would be appreciated, cool script :)

**Comment by mschuerig** [comment]
I'm sorry to say that I don't use beets anymore myself. My hunch is that beets-top seems not to be compatible with current versions of beets.
